
dataset:
  data_processed_hr: '/home/dev/data_main/DIV2K/processed_50_espcn/HR'
  data_processed_lr: '/home/dev/data_main/DIV2K/processed_50_espcn/LR'
  val_folder: '/valid/'
  train_folder: '/train/'
  scale: 4
  subset: #'/home/dev/work_main/2021/RAW_SELECTION/subset_1.0%_KCenters.txt'
  workers: 10
  train_portion: 0.7
  batch_size: 32
  debug_mode: true # run on a small porion of data
  

search:
  run_name: 'SKIP_ONLY'
  penalty: 0.0
  use_adjuster: false
  unrolled: false
  gpu: 2
  use_l1_alpha: false
  l1_lambda: 1
  use_soft_edge: true
  alpha_selector: softmax #softmax #softmax #softmax #gumbel2k #softmax 
  warm_up: 15

  channels: 3
  repeat_factor: 16
  n_nodes: 4

  log_dir: '/home/dev/data_main/LOGS/SR_DARTS/'
  im_dir: 'arch_images'
  w_lr: 1e-3 # lr for weights
  w_lr_min: 0.001 # minimum lr for weights
  w_momentum: 0.9 # momentum for weights
  w_weight_decay: 3e-4 # weight decay for weights
  w_grad_clip: 5 # gradient clipping for weights
  print_freq: 30 # print frequency
  epochs: 30 # n of training epochs
  temperature_start: 1
  temp_red: 0.6
  init_channels: 16
  layers: 4 # of layers 8 is default
  seed: 2 #random seed
  workers: 4 ## of workers
  alpha_lr:  3e-4 #3e-4 #lr for alpha
  alpha_weight_decay: 0 #1e-3 #weight decay for alpha
  train_portion: 0.5  # portion of training data
  adjuster: 
    lr: 0.001
    CL: 2e+7
    CH: 1e+8 # set some big value if no upper bound 
    max_iter: 100
    verbose: true
    gamma: 1e-6
  
  
train:
  run_name: 'TEST_Tune_BEST_founds'
  log_dir: '/home/dev/data_main/LOGS/SR_DARTS/'
  gpu: 2
  batch_size : 32 # batch size
  lr : 1e-3 # lr for weights
  momentum : 0.9 # momentum
  weight_decay : 3e-4 # weight decay
  grad_clip : 5 # gradient clipping for weights
  print_freq : 200 # print frequency
  epochs : 30 # # of training epochs
  init_channels : 36
  layers : 6 # n of layers
  seed : 2 # random seed
  workers : 4 # of workers
  aux_weight : 0.4 # auxiliary loss weight
  cutout_length : 0 # cutout length
  drop_path_prob : 0.2 # drop path prob
  genotype_path:  '/home/dev/work_main/2021/DARTS/genotype_example_sr.gen'
  
