dataset:
  data_processed_hr: '/home/dev/data_mnt/SR/DIV2K/processed/HR' 
  data_processed_lr:  '/home/dev/data_mnt/SR/DIV2K/processed/HR' 
  val_folder: '/valid/'
  train_folder: '/train/'
  scale: 4
  subset: #/home/dev/data_main/CORESETS/vmlinuz.txt
  workers: 10
  train_portion: 0.7
  batch_size: 32
  crop_size: 45 # small image,  60x4=240, pathces are 200x200
  files_list: /home/dev/data_mnt/SR
  debug_mode: false # run on a small porion of data
  

arch:
  channels: 3
  c_fixed: 32
  scale: 4
  arch_pattern: 
      head: 2
      skip: 1
      tail: 2
      body: 3
      upsample: 1
  body_cells: 2


search:
  run_name: 'DEBUG'
  penalty: 0.0
  use_adjuster: false
  unrolled: false
  gpu: 2
  use_l1_alpha: false
  l1_lambda: 1
  use_soft_edge: false
  alpha_selector: gumbel #softmax #softmax #softmax #gumbel2k #softmax 
  warm_up: 10
  lr_scheduler: cosine
  log_dir: /home/dev/data_mnt/logs
  im_dir: 'arch_images'
  w_lr: 1e-3 # lr for weights
  w_lr_min: 0.001 # minimum lr for weights
  w_momentum: 0.9 # momentum for weights
  w_weight_decay: 3e-6 # weight decay for weights
  w_grad_clip: 5 # gradient clipping for weights
  print_freq: 60 # print frequency
  epochs: 20 # n of training epochs
  temperature_start: 1e1
  temp_red: 0.6
  layers: 4 # of layers 8 is default
  seed: 2 #random seed
  workers: 4 ## of workers
  alpha_lr:  3e-4 #3e-4 #lr for alpha
  alpha_weight_decay: 0 #1e-3 #weight decay for alpha
  train_portion: 0.5  # portion of training data
  adjuster: 
    lr: 0.001
    CL: 2e+7
    CH: 1e+8 # set some big value if no upper bound 
    max_iter: 100
    verbose: true
    gamma: 1e-6
  
train:
  run_name: 'Stress test'
  log_dir: /home/dev/data_mnt/logs
  gpu: 0
  lr_scheduler: linear
  use_drop_prob: false
  drop_path_prob : 0.0
  blocks: 1
  batch_size : 16 # batch size
  lr : 1e-3 # lr for weights
  weight_decay : 0 # weight decay
  print_freq : 200 # print frequency
  epochs : 60 # # of training epochs
  seed : 777 # random seed
  workers : 8 # of workers
  genotype_path: "./genotype_example_sr.gen"
