dataset:
  data_processed_hr: '/home/dev/data_main/DIV2K/processed_50_espcn/HR'
  data_processed_lr: '/home/dev/data_main/DIV2K/processed_50_espcn/LR'
  val_folder: '/valid/'
  train_folder: '/train/'
  scale: 4
  subset: /home/dev/data_main/CORESETS/vmlinuz.txt
  workers: 10
  train_portion: 0.5
  batch_size: 32
  crop_size: 32
  files_list: '/home/dev/data_main/SR/train_sets_txt/short'
  debug_mode: false # run on a small porion of data
  

search:
  run_name: 'DEBUG'
  penalty: 0.0
  use_adjuster: false
  unrolled: false
  gpu: 3
  use_l1_alpha: false
  l1_lambda: 1
  use_soft_edge: false
  alpha_selector: softmax #softmax #softmax #softmax #gumbel2k #softmax 
  warm_up: 0

  channels: 3
  repeat_factor: 16
  n_nodes: 5
  lr_scheduler: cosine
  log_dir: '/home/dev/data_main/LOGS/SR_DARTS/'
  im_dir: 'arch_images'
  w_lr: 1e-3 # lr for weights
  w_lr_min: 0.001 # minimum lr for weights
  w_momentum: 0.9 # momentum for weights
  w_weight_decay: 3e-6 # weight decay for weights
  w_grad_clip: 5 # gradient clipping for weights
  print_freq: 60 # print frequency
  epochs: 25 # n of training epochs
  temperature_start: 1e1
  temp_red: 0.6
  layers: 4 # of layers 8 is default
  seed: 2 #random seed
  workers: 4 ## of workers
  alpha_lr:  3e-4 #3e-4 #lr for alpha
  alpha_weight_decay: 0 #1e-3 #weight decay for alpha
  train_portion: 0.5  # portion of training data
  adjuster: 
    lr: 0.001
    CL: 2e+7
    CH: 1e+8 # set some big value if no upper bound 
    max_iter: 100
    verbose: true
    gamma: 1e-6
  
  
train:
  run_name: 'ESPCN_new_set'
  log_dir: '/home/dev/data_main/LOGS/SR_DARTS/'
  gpu: 0
  lr_scheduler: cosine
  use_drop_prob: false
  drop_path_prob : 0.0
  batch_size : 32 # batch size
  lr : 1e-3 # lr for weights
  momentum : 0.9 # momentum
  weight_decay : 0 #0.0005 # weight decay
  grad_clip : 5 # gradient clipping for weights
  print_freq : 200 # print frequency
  epochs : 30 # # of training epochs
  seed : 2 # random seed
  workers : 4 # of workers
  genotype_path: /home/dev/data_main/LOGS/SR_DARTS/single_path/trail_1/SEARCH_batch experiment_penalty_0_trail_1-2021-09-22-18/best_arch.gen